### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by LadaBr** [dburckh/Media3Avi#5]
When I included source in my project build failed:

main\java\com\homesoft\exo\extractor\avi\BoxReader.java:9: error: package com.homesoft.exo.avi does not exist

import com.homesoft.exo.avi.BuildConfig;

BoxReader.java:68: error: cannot find symbol

if (BuildConfig.DEBUG && position > getEnd()) {

Where do I find this package? Thanks.

**Comment by dburckh** [comment]
Sorry it took so long to get back to you.  BuildConfig is a generated file so depending on how you pulled in the code it may not be generated.  My intention with this library is that you would build the .aar or pull it in as a module.  Anyway, I added an .aar to the latest release https://github.com/dburckh/Media3Avi/releases

Notes:

- Since this aar is not hosted, it will not have the Media3 dependencies, you will have to add them yourself.
- The code is debug code and is structured in such a way that R8 will remove it, but you can just delete it if you like.

**Comment by dburckh** [comment]
Closed as no longer relevant.
